<a href="https://colab.research.google.com/github/lkssraw-7/atividade1/blob/main/ATIVIDADE_THA%C3%8DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
#DUPLA
#Lucas Cordeiro Raw
#Lucas Ferreira

import numpy as np
import pandas as pd

from scipy.spatial.distance import squareform, pdist
from sklearn.metrics.pairwise import euclidean_distances


In [18]:
pd.options.display.float_format = '{:.2f}'.format

np.set_printoptions(precision=2, suppress=True)

df = pd.read_csv('imrs.csv')
df_salinas = df[df['nome_micro']=='Salinas']
vars = ['mun','perc_lixo','perc_esgoto','esp_vida','tx_mort_inf']

df_salinas = df_salinas[vars].dropna()

df_salinas.head()




,mun,perc_lixo,perc_esgoto,esp_vida,tx_mort_inf
9,Águas Vermelhas,97.75,29.84,73.00,0.00
70,Berizal,82.89,13.09,70.00,0.00
230,Curral de Dentro,87.65,40.56,71.00,8.55
247,Divisa Alegre,97.60,0.11,68.00,14.71
303,Fruta de Leite,82.34,0.08,73.00,29.70


In [20]:
x = df_salinas.drop(columns=['mun']).to_numpy()
print(x)


[[97.75 29.84 73.    0.  ]
 [82.89 13.09 70.    0.  ]
 [87.65 40.56 71.    8.55]
 [97.6   0.11 68.   14.71]
 [82.34  0.08 73.   29.7 ]
 [90.41 13.5  73.   13.33]
 [91.04 24.98 74.   21.05]
 [97.03  6.86 72.   19.23]
 [95.52  0.1  73.   14.93]
 [94.91  4.71 73.   10.05]
 [91.72 18.13 73.   10.1 ]
 [95.69 60.01 74.   18.15]
 [98.65 25.88 70.    0.  ]
 [95.78 21.26 72.    8.55]
 [99.58 15.13 73.   10.31]
 [98.28  6.2  74.   14.61]
 [88.58  0.37 74.   15.38]]


In [22]:
d = euclidean_distances(x,x)
d

array([[ 0.  , 22.59, 17.15, 33.55, 44.78, 22.33, 22.64, 29.99, 33.35,
        27.21, 16.6 , 35.28,  5.05, 12.31, 18.06, 27.81, 34.5 ],
       [22.59,  0.  , 29.18, 24.6 , 32.57, 15.6 , 25.82, 24.75, 23.67,
        18.02, 14.64, 52.06, 20.3 , 17.61, 19.95, 22.67, 21.14],
       [17.15, 29.18,  0.  , 42.22, 46.02, 27.69, 20.48, 36.59, 41.76,
        36.66, 22.94, 23.33, 20.26, 20.97, 28.22, 36.6 , 40.89],
       [33.55, 24.6 , 42.22,  0.  , 21.97, 16.06, 27.16,  9.07,  5.42,
         8.67, 20.14, 60.33, 29.76, 22.46, 16.55,  8.58, 10.86],
       [44.78, 32.57, 46.02, 21.97,  0.  , 22.65, 27.78, 19.3 , 19.8 ,
        23.78, 28.25, 62.48, 42.69, 32.83, 29.99, 22.81, 15.66],
       [22.33, 15.6 , 27.69, 16.06, 22.65,  0.  , 13.88, 11.12, 14.43,
        10.41,  5.8 , 47.07, 20.2 , 10.63,  9.79, 10.86, 13.45],
       [22.64, 25.82, 20.48, 27.16, 27.78, 13.88,  0.  , 19.28, 26.03,
        23.41, 12.97, 35.46, 22.76, 14.02, 16.92, 21.13, 25.37],
       [29.99, 24.75, 36.59,  9.07, 19.3 , 11.12

In [23]:
df_dist = pd.DataFrame(
    d,
    index=df_salinas['mun'],
    columns=df_salinas['mun']
)
df_dist

mun,Águas Vermelhas,Berizal,Curral de Dentro,Divisa Alegre,Fruta de Leite,Indaiabira,Montezuma,Ninheira,Novorizonte,Rio Pardo de Minas,Rubelita,Salinas,Santa Cruz de Salinas,Santo Antônio do Retiro,São João do Paraíso,Taiobeiras,Vargem Grande do Rio Pardo
mun,,,,,,,,,,,,,,,,,
Águas Vermelhas,0.00,22.59,17.15,33.55,44.78,22.33,22.64,29.99,33.35,27.21,16.60,35.28,5.05,12.31,18.06,27.81,34.50
Berizal,22.59,0.00,29.18,24.60,32.57,15.60,25.82,24.75,23.67,18.02,14.64,52.06,20.30,17.61,19.95,22.67,21.14
Curral de Dentro,17.15,29.18,0.00,42.22,46.02,27.69,20.48,36.59,41.76,36.66,22.94,23.33,20.26,20.97,28.22,36.60,40.89
Divisa Alegre,33.55,24.60,42.22,0.00,21.97,16.06,27.16,9.07,5.42,8.67,20.14,60.33,29.76,22.46,16.55,8.58,10.86
Fruta de Leite,44.78,32.57,46.02,21.97,0.00,22.65,27.78,19.30,19.80,23.78,28.25,62.48,42.69,32.83,29.99,22.81,15.66
Indaiabira,22.33,15.60,27.69,16.06,22.65,0.00,13.88,11.12,14.43,10.41,5.80,47.07,20.20,10.63,9.79,10.86,13.45
Montezuma,22.64,25.82,20.48,27.16,27.78,13.88,0.00,19.28,26.03,23.41,12.97,35.46,22.76,14.02,16.92,21.13,25.37
Ninheira,29.99,24.75,36.59,9.07,19.30,11.12,19.28,0.00,8.21,9.72,15.48,53.22,27.17,17.97,12.47,5.23,11.50
Novorizonte,33.35,23.67,41.76,5.42,19.80,14.43,26.03,8.21,0.00,6.74,19.05,60.01,30.10,22.13,16.24,6.78,7.03


In [31]:
np.fill_diagonal(d,np.inf)

indice_min = np.unravel_index(np.argmin(d),d.shape)

mun1= df_salinas['mun'].iloc[indice_min[0]]
mun2= df_salinas['mun'].iloc[indice_min[1]]

print("Municípios mais semelhantes:")
print(mun1, "e", mun2)

Municípios mais semelhantes:
Águas Vermelhas e Santa Cruz de Salinas


In [35]:
d_max = d.copy()
np.fill_diagonal(d_max, -np.inf)

indice_max = np.unravel_index(np.argmax(d_max), d_max.shape)

mun1_max = df_salinas['mun'].iloc[indice_max[0]]
mun2_max = df_salinas['mun'].iloc[indice_max[1]]

print("\nMunicípios menos semelhantes:")
print(mun1_max, "e", mun2_max)


Municípios menos semelhantes:
Fruta de Leite e Salinas
